apiVersion: v1
appVersion: "1.6"
description: Deploys a cronJob which will renew ECR imagePullSecrets automatically
name: k8s-ecr-login-renew
version: "0.1"
maintainers:
- email: james@tachibana.systems
  name: James "ec0" Hebden
keywords:
- aws
- ecr
- imagePullSecrets
sources:
 - https://github.com/nabsul/k8s-ecr-login-renew
