apiVersion: v2
name: k8s-ecr-login-renew
version: 1.0.6
appVersion: 1.7.2
description: Deploys a cronJob which will renew ECR imagePullSecrets automatically
maintainers:
- name: Nabeel Sulieman
  url: https://nabeel.dev
keywords:
- aws
- ecr
- imagePullSecrets
sources:
 - https://github.com/nabsul/k8s-ecr-login-renew
