apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-ecr-login-renew.secret" . }}
  labels:
{{ include "k8s-ecr-login-renew.labels" . | indent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.ecr.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ecr.secretAccessKey }}
  AWS_REGION: {{ .Values.ecr.region }}
  DOCKER_SECRET_NAME: {{ .Values.secretName }}
